### ISSUE TITLE
I am getting 500 error

### ISSUE THREAD

**Issue by mallikarjunece** [NARKOZ/ginatra#33]
How to resolve 500 error
![screenshot from 2015-01-12 20 52 35](https://cloud.githubusercontent.com/assets/1826210/5705141/f67c8116-9a9c-11e4-817d-97f443ed5863.png)

**Comment by abrausch** [comment]
Same for me. Is there some possibility to enable some kind of logging? Or a verbose mode?

**Comment by NARKOZ** [comment]
Did you set the correct path(s) for `git_dirs` in config.yml?

Check that

- it ends with an asterisk `*` (it is a glob)
- doesn't contain anything but folders with git repositories

Path should be absolute. https://github.com/NARKOZ/ginatra#configuration

Verbose mode is available if ginatra installed as an app. Just export `RACK_ENV` before starting server:

```
RACK_ENV=development ./bin/ginatra run
```

**Comment by abrausch** [comment]
Yes for me it was a problem with my git_dirs. Is there a reason why it is not allowed to have non git directories inside the same folder?

**Comment by NARKOZ** [comment]
Thanks for the reports. I've released version 4.0.2 that changes this behaviour.

**Comment by abrausch** [comment]
Very nice, thanks :+1:

**Comment by rogermarlow** [comment]
I have been having similar problems. There isn't much handling of cases where the user config file is absent or broken. I'd like to be able to specify a git repo on the command line at startup too. And some of my repos don't have .git/describe files which also causes a fail. Unless anyone else is working on this I'm happy to fork and do some work towards some pull requests.

**Comment by NARKOZ** [comment]
@rogermarlow pull requests are appreciated. 

On the other hand, each git repo has `.git/describe` file by default, so that's a bit strange.

**Comment by rogermarlow** [comment]
@NARKOZ agreed, but some repos were set-up a very long time ago, and I don't know when the description file convention came in. Looks like some geolite users might be in this situation depending on when they initialised their repos. See this StackOverflow thread http://stackoverflow.com/q/13015001/327074 . No big deal, it's easy to deal with.
