### ISSUE TITLE
Running the rspecs

### ISSUE THREAD

**Issue by rogermarlow** [NARKOZ/ginatra#34]
When I clone the ginatra repo and run the rspecs I get failures. Do the rspecs expect there to be a "test" repo somewhere? I see hashes in the rspecs, e.g. "it returns a link for a commit patch" helpers_spec.rb:67, so presumably there are some pre-existing commits by a specific user that need to be in that repo (i.e. I can't just git init and add some commits myself)?

**Comment by NARKOZ** [comment]
Yes, you should clone github.com/atmos/hancock-client into `repos/test`. 



`bundle exec rake` will do that for you if you didn't. 


https://github.com/NARKOZ/ginatra/blob/master/Rakefile

**Comment by NARKOZ** [comment]
There is a task to clone test repo: `rake clone_repo`

**Comment by rogermarlow** [comment]
OK, I see the problem. The rake tasks are all fine but if I have a user config file, ~/.ginatra/config.yml, its git_dirs overrides the gem's git_dirs which says where the test repo is. So unless the user's config.yml git_dirs contain ginatra/repos/* the rspecs can't find the test repo. When I put that path in my git_dirs all the rspecs pass.

**Comment by NARKOZ** [comment]
74330f0dd9526b6fefc55a1052b11aa7b3d12749
