### ISSUE TITLE
add logger to log errors and warnings

### ISSUE THREAD

**Issue by NARKOZ** [NARKOZ/ginatra#41]

**Comment by JahlomP** [comment]
On Saturday, April 18, 2015, Nihad Abbasov <notifications@github.com> wrote:
> —
> Reply to this email direcytly or view it on GitHub.<
https://ci4.googleusercontent.com/proxy/TgWAoCndZSpIUaakaMV8Te1ymPhqU7Hwf1YDMfCytNV2oLuwELJ8s2GraoUc-7qoU9W3xhRI90OFUK3I1tv-MB5Wa_BVblof-_tshh3lmrT5ZpYvAKUWr-F5iBEVH_VdwQM_F0mdgoqNCwBkYFQBK_Z2T35r9g=s0-d-e1-ft#https://github.com/notifications/beacon/AEhtD7qU-QwutyA23U_3QK0KhF7Kpuybks5oAjumgaJpZM4EDVKG.gif
>

-- 
Best Rregards,
Precious Jahlom Agboado,
NibbleIT,
www.twitter.com/jahlomp
+233 54 0915 108.

**Comment by NARKOZ** [comment]
https://github.com/NARKOZ/ginatra/compare/7c6ca20801...91303d98bc
